<a href="https://colab.research.google.com/github/saurabhtayal/Capstone-Project---Diabetic-Patients-Readmission-Prediction/blob/master/Creating_Insulin_Treatment_Feature_Saurabh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('/content/drive/My Drive/PGPDSE/Capstone/CSV Files/Diabetes_Preprocessed.csv')
df.head()

              race  gender  ...  number_diab_meds number_changes
0        Caucasian       0  ...                 0              0
1        Caucasian       0  ...                 1              1
2  AfricanAmerican       0  ...                 1              0
3        Caucasian       1  ...                 1              1
4        Caucasian       1  ...                 2              0

[5 rows x 46 columns]

In [3]:
df.shape

(97070, 46)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97070 entries, 0 to 97069
Data columns (total 46 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   race                      97070 non-null  object
 1   gender                    97070 non-null  int64
 2   age                       97070 non-null  int64
 3   admission_type_id         97070 non-null  object
 4   discharge_disposition_id  97070 non-null  object
 5   admission_source_id       97070 non-null  object
 6   time_in_hospital          97070 non-null  int64
 7   num_lab_procedures        97070 non-null  int64
 8   num_procedures            97070 non-null  int64
 9   num_medications           97070 non-null  int64
 10  number_outpatient         97070 non-null  int64
 11  number_emergency          97070 non-null  int64
 12  number_inpatient          97070 non-null  int64
 13  diag_1                    97070 non-null  object
 14  diag_2                    97070 non-null  object
 15  diag_3                    97070 non-null  object
 16  number_diagnoses          97070 non-null  int64
 17  max_glu_serum             97070 non-null  object
 18  A1Cresult                 97070 non-null  object
 19  metformin                 97070 non-null  int64
 20  repaglinide               97070 non-null  int64
 21  nateglinide               97070 non-null  int64
 22  chlorpropamide            97070 non-null  int64
 23  glimepiride               97070 non-null  int64
 24  acetohexamide             97070 non-null  int64
 25  glipizide                 97070 non-null  int64
 26  glyburide                 97070 non-null  int64
 27  tolbutamide               97070 non-null  int64
 28  pioglitazone              97070 non-null  int64
 29  rosiglitazone             97070 non-null  int64
 30  acarbose                  97070 non-null  int64
 31  miglitol                  97070 non-null  int64
 32  troglitazone              97070 non-null  int64
 33  tolazamide                97070 non-null  int64
 34  insulin                   97070 non-null  int64
 35  glyburide-metformin       97070 non-null  int64
 36  glipizide-metformin       97070 non-null  int64
 37  glimepiride-pioglitazone  97070 non-null  int64
 38  metformin-rosiglitazone   97070 non-null  int64
 39  metformin-pioglitazone    97070 non-null  int64
 40  change                    97070 non-null  int64
 41  diabetesMed               97070 non-null  int64
 42  readmitted                97070 non-null  int64
 43  preceding_year_visits     97070 non-null  int64
 44  number_diab_meds          97070 non-null  int64
 45  number_changes            97070 non-null  int64
dtypes: int64(37), object(9)
memory usage: 34.1+ MB

In [5]:
df.columns

Index(['race', 'gender', 'age', 'admission_type_id',
       'discharge_disposition_id', 'admission_source_id', 'time_in_hospital',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'insulin', 'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted',
       'preceding_year_visits', 'number_diab_meds', 'number_changes'],
      dtype='object')

In [6]:
meds = ['metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'insulin', 'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone']

In [7]:
df['insulin_treatment'] = np.nan

In [8]:
for i in range(len(df)):
    if df.loc[i, 'insulin'] != -2 and df.loc[i, 'number_diab_meds'] == 1:
        df.loc[i, 'insulin_treatment'] = 'insulin_only'
    elif df.loc[i, 'insulin'] != -2 and df.loc[i, 'number_diab_meds'] > 1:
        df.loc[i, 'insulin_treatment'] = 'insulin_combo'
    elif df.loc[i, 'insulin'] == -2 and df.loc[i, 'number_diab_meds'] == 0:
        df.loc[i, 'insulin_treatment'] = 'no_med'
    else:
        df.loc[i, 'insulin_treatment'] = 'other_meds'
df['insulin_treatment'].value_counts()

insulin_only     29118
other_meds       23259
insulin_combo    22465
no_med           22228
Name: insulin_treatment, dtype: int64

In [9]:
df['insulin'].value_counts()

-2    45487
 0    29118
-1    11735
 1    10730
Name: insulin, dtype: int64

In [10]:
df.head()

              race  gender  ...  number_changes insulin_treatment
0        Caucasian       0  ...               0            no_med
1        Caucasian       0  ...               1      insulin_only
2  AfricanAmerican       0  ...               0        other_meds
3        Caucasian       1  ...               1      insulin_only
4        Caucasian       1  ...               0     insulin_combo

[5 rows x 47 columns]

In [11]:
df.to_csv('/content/drive/My Drive/PGPDSE/Capstone/CSV Files/Diabetes_Preprocessed.csv', index = False)

In [12]:
df.to_csv('Diabetes_Preprocessed.csv', index = False)